### PR TITLE
Build with both GCC 7 & 9

### PR DESCRIPTION
**Pull request by jakirkham**
As we use this with some older CUDA versions where GCC 7 is required, build this with GCC 7 as well as GCC 9.

cc @hcho3 @JohnZed @kkraus14

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by chyunsu3** [comment]
For some reason, the PPC64LE builds on Travis CI are very flaky, crashing without any stack trace.

**Review by hcho3 — APPROVED** [review]

**Comment by jakirkham** [comment]
Yeah I've been seeing that as well. Have restarted ones that appeared to be wonky, which cleared some of the errors. That said, maybe we can just merge and restart the jobs on `master` instead since we know these are just flaky. WDYT? :)

**Comment by chyunsu3** [comment]
Merged. Thanks!

**Comment by jakirkham** [comment]
Took a bit of restarting, but it looks like Travis CI now passes on `master`.

**Comment by isuruf** [comment]
Please revert this PR. There's no reason to add GCC 7 & 9 builds for C/C++ packages. One is enough. This is against what we discussed in core meetings.

cc @conda-forge/core

**Comment by jakirkham** [comment]
> Please revert this PR. There's no reason to add GCC 7 & 9 builds for C/C++ packages. One is enough. This is against what we discussed in core meetings.
> 
> cc @conda-forge/core

I'm happy to discuss with you why this was needed at the core meeting tomorrow.

cc @kkraus14 (for vis)

**Pull request merged**
