### PR TITLE
Upgrade to Treelite 1.1.0

### PR DESCRIPTION
**Pull request by hcho3**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

Closes https://github.com/conda-forge/treelite-feedstock/pull/24

### CODE REVIEW

**Comment by chyunsu3** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Pushed a commit to your PR to move from Travis CI to Azure with that build (hope that is ok :). Travis CI was having some issues recently and haven't heard back from them yet. This should hopefully unblock things while Travis CI sorts out this issue

Edit: Also added a closes note to the OP to close out the bot update PR once this is merged. Again hope this is ok

**Comment by chyunsu3** [comment]
@jakirkham Thanks for your help 😄

**Pull request merged**
